// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grievance.Data;

#nullable disable

namespace grievance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("grievance.Models.Grievance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForwardedToPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("PrincipalRemarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeacherRemarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grievances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Department = 0,
                            Description = "Computers in Lab 3 crash constantly during practicals.",
                            ForwardedToPrincipal = false,
                            PrincipalRemarks = "",
                            Status = 0,
                            StudentId = 8,
                            SubmittedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherRemarks = "",
                            Title = "Lab computers outdated"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Department = 0,
                            Description = "Two exams scheduled the same day with no break.",
                            ForwardedToPrincipal = false,
                            PrincipalRemarks = "",
                            Status = 1,
                            StudentId = 9,
                            SubmittedAt = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherRemarks = "",
                            Title = "Exam schedule conflict"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Department = 1,
                            Description = "No AC in Room 204, causing discomfort during lectures.",
                            ForwardedToPrincipal = true,
                            PrincipalRemarks = "",
                            Status = 3,
                            StudentId = 10,
                            SubmittedAt = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherRemarks = "",
                            Title = "Classroom ventilation issue"
                        });
                });

            modelBuilder.Entity("grievance.Models.InternalMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int>("MaxMark")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("InternalMarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 0,
                            Grade = "B+",
                            Mark = 38,
                            MaxMark = 50,
                            StudentId = 8,
                            SubjectCode = "CS301",
                            SubjectName = "Data Structures",
                            TeacherId = 2,
                            UpdatedAt = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Department = 0,
                            Grade = "A",
                            Mark = 45,
                            MaxMark = 50,
                            StudentId = 8,
                            SubjectCode = "CS302",
                            SubjectName = "Operating Systems",
                            TeacherId = 2,
                            UpdatedAt = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Department = 0,
                            Grade = "A",
                            Mark = 42,
                            MaxMark = 50,
                            StudentId = 9,
                            SubjectCode = "CS301",
                            SubjectName = "Data Structures",
                            TeacherId = 2,
                            UpdatedAt = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Department = 1,
                            Grade = "B+",
                            Mark = 40,
                            MaxMark = 50,
                            StudentId = 10,
                            SubjectCode = "AI201",
                            SubjectName = "Machine Learning",
                            TeacherId = 3,
                            UpdatedAt = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("grievance.Models.RevaluationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarkId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherFeedback")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarkId")
                        .IsUnique();

                    b.ToTable("RevaluationRequests");
                });

            modelBuilder.Entity("grievance.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 0,
                            Email = "principal@college.edu",
                            EmployeeId = "",
                            Name = "Dr. S. Krishnamurthy",
                            PasswordHash = "IZDj5oIcw1aQaFyKgfSdJgN56OkGpb9+P91APezA9Vs=",
                            Role = "Principal",
                            RollNumber = ""
                        },
                        new
                        {
                            Id = 2,
                            Department = 0,
                            Email = "ravi@college.edu",
                            EmployeeId = "T001",
                            Name = "Prof. Ravi Kumar",
                            PasswordHash = "XIEzXxRWVJmnVwvxlDClAwryKSgCyyHdBpN9rME6WWM=",
                            Role = "Teacher",
                            RollNumber = ""
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "meena@college.edu",
                            EmployeeId = "T002",
                            Name = "Prof. Meena Sharma",
                            PasswordHash = "XIEzXxRWVJmnVwvxlDClAwryKSgCyyHdBpN9rME6WWM=",
                            Role = "Teacher",
                            RollNumber = ""
                        },
                        new
                        {
                            Id = 4,
                            Department = 2,
                            Email = "suresh@college.edu",
                            EmployeeId = "T003",
                            Name = "Prof. Suresh Nair",
                            PasswordHash = "XIEzXxRWVJmnVwvxlDClAwryKSgCyyHdBpN9rME6WWM=",
                            Role = "Teacher",
                            RollNumber = ""
                        },
                        new
                        {
                            Id = 5,
                            Department = 4,
                            Email = "anjali@college.edu",
                            EmployeeId = "T004",
                            Name = "Prof. Anjali Pillai",
                            PasswordHash = "XIEzXxRWVJmnVwvxlDClAwryKSgCyyHdBpN9rME6WWM=",
                            Role = "Teacher",
                            RollNumber = ""
                        },
                        new
                        {
                            Id = 6,
                            Department = 3,
                            Email = "deepak@college.edu",
                            EmployeeId = "T005",
                            Name = "Prof. Deepak Menon",
                            PasswordHash = "XIEzXxRWVJmnVwvxlDClAwryKSgCyyHdBpN9rME6WWM=",
                            Role = "Teacher",
                            RollNumber = ""
                        },
                        new
                        {
                            Id = 7,
                            Department = 5,
                            Email = "latha@college.edu",
                            EmployeeId = "T006",
                            Name = "Prof. Latha Rao",
                            PasswordHash = "XIEzXxRWVJmnVwvxlDClAwryKSgCyyHdBpN9rME6WWM=",
                            Role = "Teacher",
                            RollNumber = ""
                        },
                        new
                        {
                            Id = 8,
                            Department = 0,
                            Email = "arjun@student.edu",
                            EmployeeId = "",
                            Name = "Arjun Dev",
                            PasswordHash = "J8MWMBT7tpZyQsqEXAy9pdVczg8Ay/pARXfdIqJelXg=",
                            Role = "Student",
                            RollNumber = "CSE001"
                        },
                        new
                        {
                            Id = 9,
                            Department = 0,
                            Email = "priya@student.edu",
                            EmployeeId = "",
                            Name = "Priya Menon",
                            PasswordHash = "J8MWMBT7tpZyQsqEXAy9pdVczg8Ay/pARXfdIqJelXg=",
                            Role = "Student",
                            RollNumber = "CSE002"
                        },
                        new
                        {
                            Id = 10,
                            Department = 1,
                            Email = "rahul@student.edu",
                            EmployeeId = "",
                            Name = "Rahul Krishnan",
                            PasswordHash = "J8MWMBT7tpZyQsqEXAy9pdVczg8Ay/pARXfdIqJelXg=",
                            Role = "Student",
                            RollNumber = "AIML001"
                        },
                        new
                        {
                            Id = 11,
                            Department = 2,
                            Email = "sneha@student.edu",
                            EmployeeId = "",
                            Name = "Sneha Thomas",
                            PasswordHash = "J8MWMBT7tpZyQsqEXAy9pdVczg8Ay/pARXfdIqJelXg=",
                            Role = "Student",
                            RollNumber = "MECH001"
                        });
                });

            modelBuilder.Entity("grievance.Models.Grievance", b =>
                {
                    b.HasOne("grievance.Models.User", "Student")
                        .WithMany("Grievances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("grievance.Models.InternalMark", b =>
                {
                    b.HasOne("grievance.Models.User", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("grievance.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("grievance.Models.RevaluationRequest", b =>
                {
                    b.HasOne("grievance.Models.InternalMark", "Mark")
                        .WithOne("RevaluationRequest")
                        .HasForeignKey("grievance.Models.RevaluationRequest", "MarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mark");
                });

            modelBuilder.Entity("grievance.Models.InternalMark", b =>
                {
                    b.Navigation("RevaluationRequest");
                });

            modelBuilder.Entity("grievance.Models.User", b =>
                {
                    b.Navigation("Grievances");

                    b.Navigation("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
